// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pitvpkbkoleqpoihylbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpdHZwa2Jrb2xlcXBvaWh5bGJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzE3NzQsImV4cCI6MjA2MzY0Nzc3NH0.G9mac4bZBxlC8GA8Tcn4lfPYDOBbmjd_m5CHI575dFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);